name: Build

on:
  push:
    branches:
    - main
  pull_request:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v6
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v5
    - name: Build with dotnet
      run: dotnet build -bl -c release -m:1
    - name: Pack projects
      run: |
        dotnet pack src/RoslynPad.Editor.Avalonia --configuration Release -bl -m:1
        dotnet pack src/RoslynPad.Roslyn.Avalonia --configuration Release -bl -m:1
        dotnet pack src/RoslynPad.Roslyn --configuration Release -bl -m:1
    - name: Set up nuget
      run: dotnet nuget add source --username USERNAME --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/rosslight/index.json"
    - run: |
        ls -l
        ls -l src
        ls -l src/RoslynPad.Editor.Avalonia
        ls -l src/RoslynPad.Editor.Avalonia/bin/Release
    - name: Push
      run: |
        dotnet nuget push "src/RoslynPad.Editor.Avalonia/bin/Release/*.nupkg" --skip-duplicate --api-key ${{ github.token }} --source "github"
        dotnet nuget push "src/RoslynPad.Roslyn.Avalonia/bin/Release/*.nupkg" --skip-duplicate --api-key ${{ github.token }} --source "github"
        dotnet nuget push "src/RoslynPad.Roslyn/bin/Release/*.nupkg" --skip-duplicate --api-key ${{ github.token }} --source "github"
